---
apiVersion: v1
kind: Secret
metadata:
  name: acme-messaging-demo-credentials
type: Opaque
data:
  data: c2VjcmV0

---
apiVersion: cp.nuodb.com/v1beta1
kind: Database
metadata:
  name: acme-messaging-demo
  labels:
    cp.nuodb.com/organization: "acme"
    cp.nuodb.com/project: "messaging"
spec:
  version: "5.0"
  type: 
    tierRef: 
      name: n0.small
    sla: dev
  dbName: demo
  domainRef: 
    name: acme-messaging
  passwordRef:
    kind: Secret
    name: acme-messaging-demo-credentials
  archiveVolume:
    volumeSize: 10Gi
  journalVolume:
    volumeSize: 5Gi
