---
apiVersion: v1
kind: ConfigMap
metadata:
  name: acme-messaging-demo-info
  annotations:
    cp.nuodb.com/inject-database: "acme-messaging-demo"
data: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsb-load
  labels:
    app: ycsb-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ycsb-load
  template:
    metadata:
      labels:
        app: ycsb-load
    spec:
      containers:
      - name: ycsb-load
        image: docker.io/nuodb/ycsb:latest
        imagePullPolicy: Always
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: dbName
              name: acme-messaging-demo-info
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: dbUser
              name: acme-messaging-demo-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: dbPassword
              name: acme-messaging-demo-credentials
        - name: PEER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: dbHost
              name: acme-messaging-demo-info
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NO_OF_PROCESSES
          value: "2"
        - name: NO_OF_ITERATIONS
          value: "0"
        resources:  
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
